---
title: "Lab 02 - Plastic waste"
author: "Steve"
date: "04/26/2025"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read.csv("data/plastic-waste.csv")
glimpse(plastic_waste)
```

## Exercises

### Exercise 1

Distribution

```{r plastic-waste-continent}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap)) + geom_histogram(binwidth = 0.2)

# finding the outlier
plastic_waste %>%
  filter(plastic_waste_per_cap > 3.5)
```

### Exercise 2

```{r plastic-waste-density}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, color = continent, fill = continent)) + geom_density(alpha = 0.5, adjust = 2)
```

### Exercise 3

```{r plastic-waste-violin}
ggplot(
  data = plastic_waste,
  mapping = aes(
    x = continent,
    y = plastic_waste_per_cap
  )
) +
  geom_violin()

```

### Exercise 4

```{r plastic-waste-mismanaged}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, y = mismanaged_plastic_waste_per_cap)) + geom_point()
```

```{r plastic-waste-mismanaged-continent}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, y = mismanaged_plastic_waste_per_cap, color = continent)) + geom_point()
```

```{r plastic-waste-population-total}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, y = total_pop, color = continent)) + geom_point()
```

```{r plastic-waste-population-coastal}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, y = coastal_pop, color = continent)) + geom_point()
```

### Exercise 5

```{r recreate-viz}
ggplot(plastic_waste %>% filter(plastic_waste_per_cap < 3), aes(y = plastic_waste_per_cap, x = coastal_pop/total_pop, color = continent)) + geom_point() + geom_smooth(aes(group = 1), method = "loess", color = "black", se = TRUE) + labs(x = "Costal population proportion", y = "Plastic waste per capita",  title = "Plastic Waste vs. Costal Population Proportion",
  subtitle = "continent")
```
Higher costal population proportion is associated with higher plastic waster per capita, but the relationship is not strong

